version: '3'
services:
#  frontend:
#    build: ./frontend
#    container_name: "frontend"
#    ports:
#      - '3000:3000'
#    volumes:
#      - ./frontend:/app
#    command: npm run dev
#
#  cms:
#    build: ./cms
#    container_name: "cms"
#    ports:
#      - '1337:1337'
#    depends_on:
#      - db
#    environment:
#      DATABASE_CLIENT: postgres
#      DATABASE_HOST: db
#      DATABASE_PORT: 5432
#      DATABASE_NAME: cms-db
#      DATABASE_USERNAME: postgres
#      DATABASE_PASSWORD: postgres
#    volumes:
#      - ./cms:/opt/app

  db:
    image: postgres:14.5-alpine
    container_name: "db"
    platform: linux/amd64 #for platform error on Apple M1 chips
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./_docker_volumes/postgres:/var/lib/postgresql/data
