version: '3'
services:

  frontend:
    build: ./frontend
    container_name: "frontend"
    ports:
      - '3000:3000'
    depends_on:
      - cms
    volumes:
      - ./frontend:/app

  cms:
    build: ./cms
    container_name: "cms"
    ports:
      - '1337:1337'
    depends_on:
      - db
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./cms:/srv/app

  db:
    image: postgres:12.0-alpine
    container_name: "db"
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi