version: '3'
services:
  frontend:
    build: ./frontend
    container_name: "frontend"
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app

  cms:
    container_name: cms
    build: ./cms
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: development
    volumes:
      - ./_docker_volumes/public/uploads:/opt/app/public/uploads
      - ./cms/config:/opt/app/config
      - ./cms/src:/opt/app/src
      - ./cms/package.json:/opt/package.json
      - ./cms/package-lock.json:/opt/package-lock.json
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    container_name: "postgres"
    platform: linux/amd64 #for platform error on Apple M1 chips
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./_docker_volumes/postgres:/var/lib/postgresql/data
